from randomiser import playerValue
from random import randint, uniform

from cs50 import SQL

db = SQL("sqlite:///champgaffer.db")

# returns random news story, taking dictionary as an argument - generated by database query in generator.gotNews(user) function
def getStory(clubDict, default):
    userId = clubDict[0]['id']
    firstName = clubDict[0]['name'].split()[0].capitalize()

    Story = dict.fromkeys(["Mail_id", "Sender", "Subject", "Body", "Player_id", "Club_id"])
    if default != 0:
        item = default
    else:
        item = randint(2,18)

    Story['Mail_id'] = item
    Story['Player_id'] = None
    Story['Club_id'] = None
     
    if item == 1:
        if clubDict[0]['current_season'] - clubDict[0]['season'] == 0:
            Story['Sender'] = "The Chairman"
            Story['Subject'] = "Welcome to the club!"
            Story['Body'] = f"Hi {firstName},\nGreat to have you on board! We're confident that you're the right man to take the team forward. Anything less than a mid-table finish this season would be really disappointing. As we discussed in the interview, we're happy to invest - so we've allocated £{clubDict[0]['budget']}M as transfer funds. Good luck!\nWarm Regards,\nGlenn\n"
        else:
            Story['Sender'] = "The Chairman"
            Story['Subject'] = f"{clubDict[0]['current_season']} Expectations"
            if clubDict[0]['rank'] > 3:
                Story['Body'] = f"Hi {firstName},\nThanks yet again for working so hard to make last season a success. I never doubted that you're the man for the job. Same again this time around please {firstName} - we want to be challenging for that title! We're giving you £{clubDict[0]['budget']}M in the transfer kitty to keep us competetive.\nStay Classy,\nGlenn\n"   
            elif clubDict[0]['rank'] > 7:
                Story['Body'] = f"Hi {firstName},\nWe had a good showing last time out - it looks like we're on the right track! We want to make sure that we're moving forward, so we're providing £{clubDict[0]['budget']}M for new players.\nKeep it real,\nGlenn"
            elif clubDict[0]['rank'] > 11:
                Story['Body'] = f"Hi {firstName},\nIt's great to be in the top league isn't it? We'd very much like to get comfortable here, so I want you to concentrate on steadying the ship this year. I've put £{clubDict[0]['budget']}M aside for transfers.\nGood luck champ,\nGlenn"
            elif clubDict[0]['rank'] > 16:
                Story['Body'] = f"Hi {firstName},\nLast season was so-so but I think that we can do better. Let's give the fans something to shout about this season and push for promotion. I've put £{clubDict[0]['budget']}M into the transfer account for you to play with. Let's do this!\nWarm Regards,\nGlenn"
            else:
                Story['Body'] = f"Hi {firstName},\nI think we can both agree that last season was a little disappointing. We expect at least a mid-table finish this time around to keep things stable. We've allocated £{clubDict[0]['budget']}M to spend on players. Spend it wisely and let's get cracking!\nWarm Regards,\nGlenn"
    else:
        if item < 5 or item == 12:
            club = getRandomClub(userId)[0]
            Story['Club_id'] = club['club_id']

        if item < 10:
            player = getUserPlayer(userId)[0]
            Story['Player_id'] = player['player_id']

        if item == 2: 
            Story['Sender'] = club['manager']
            Story['Subject'] = "Transfer Offer"
            Story['Body'] = f"Hi {firstName},\nI like the look of {player['name']} and want to recruit him for {club['club_name']}. We're a bit hard up at the minute but I've pushed the chairman hard and we can stretch to £{round(playerValue(player['ovr'], player['handsomeness'], player['potential']) * uniform(0.5,0.7),1)}M. What do you think?\nRegards,\n{club['manager']}"
        
        elif item == 3:
            Story['Sender'] = club['manager']
            Story['Subject'] = "Transfer Offer"
            Story['Body'] = f"Hi {firstName},\nWe're looking to rebuild the squad at {club['club_name']} and I think that {player['name']} would be a great addition for us. Is he available? The chairman's being generous with this one so we can offer up to £{round(playerValue(player['ovr'], player['handsomeness'], player['potential']) * uniform(1.2, 1.8), 1)}M sound?\nThanks,\n{club['manager']}"
        
        elif item == 4:
            Story['Sender'] = club['manager']
            Story['Subject'] = "Transfer Offer"
            Story['Body'] = f"Hi {firstName},\nI've been admiring {player['name']} for a while now and would like to bring him to {club['club_name']}. How does £{playerValue(player['ovr'], player['handsomeness'], player['potential'])}M sound?\nThanks,\n{club['manager']}"
        
        elif item == 5:
            Story['Sender'] = "The Chairman"
            Story['Subject'] = player['name']
            Story['Body'] = f"Hi {firstName},\n{player['name']} has been out on the town again. It doesn't seem to be affecting his performances but apparently his moves are atrocious. Could you offer a quiet word of advice? And maybe a few dance lessons.\nWarm Regards,\nGlenn"

        elif item == 6:
            Story['Sender'] = "The Chairman"
            Story['Subject'] = player['name']
            Story['Body'] = f"Hi {firstName},\n{player['name']} has been sulking about the place recently and it's bringing me down. Could you see what is bothering with him? Also, have you seen my stapler? Morag only got me a new one on the last stationery order and its already gone AWOL.\nWarm Regards,\nGlenn"
        
        elif item == 7:
            Story['Sender'] = "The Chairman"
            Story['Subject'] = player['name']
            Story['Body'] = f"Hi {firstName},\nThe locker room showers are dripping again and our water bill is going to be through the roof. {player['name']}'s uncle is a plumber if I remember rightly. Could you ask him what he'd charge to have a look at it?\nWarm Regards,\nGlenn"

        elif item == 8:
            Story['Sender'] = "Head Coach"
            Story['Subject'] = player['name']
            Story['Body'] = f"Hi {firstName},\nI've been really impressed with {player['name'].split()[0]} in training this week gaffer. Did you see that overhead kick?! I'm not sure that it warranted the obscenity of the celebration though. Can't have him pulling that one in front of the family stand.\nCheers,\nDave"

        elif item == 9:
            Story['Sender'] = "Head Coach"
            Story['Subject'] = player['name']
            Story['Body'] = f"Hi {firstName},\n{player['name'].split()[0]} was struggling to keep up with today's training session. He's just got a new Instagram model girlfriend and I don't think he's getting his 8 hours sleep. You might need to ask him where his priorities lie.\nCheers,\nDave"
        
        elif item == 10:
            Story['Sender'] = "Secretary to the Chairman"
            Story['Subject'] = "Stationery"
            Story['Body'] = f"Hi {firstName},\nGlenn's lost his stapler again. I'm going to put it on a darn chain around his neck if it happens again.\nAnyway, I'm going to do another stationery order. Would you like anything?\nBest,\nMorag"

        elif item == 11:
            Story['Sender'] = "Secretary to the Chairman"
            Story['Subject'] = "Biscuits"
            Story['Body'] = f"Hi {firstName},\nI'm going to get some more biscuits in, but could we store them in your office going forward? Glenn can inhale an entire packet of chocolate hobnobs in a matter of minutes when left to his own devices.\nBest,\nMorag"

        elif item == 12:
            Story['Sender'] = "Head Coach"
            Story['Subject'] = "Espionage"
            Story['Body'] = f"Hi {firstName},\nI'm sure that you've heard the news about {club['club_name']} antics, spying on their opponents. We are doing daily patrols around the perimeter of the training ground to keep an eye out for any suspicous activity. Glenn was toying with the idea of shipping in some 'trained' coyotes from one of his friends in Mexico, but I talked him out of it.\nCheers,\nDave"

        elif item == 13:
            Story['Sender'] = "The Chairman"
            Story['Subject'] = "Going Viral"
            Story['Body'] = f"Hi {firstName},\nI've just been doing some internet research and it seems that the kids are all about this 'TikTok'. I think that we should make a few videos. I read that some of these kids are making millions. MILLIONS!\nI have a few ideas already. Could you come and install it on my phone when you get a minute please {firstName}?\nWarm Regards,\nGlenn"
        
        elif item == 14:
            Story['Sender'] = "The Chairman"
            Story['Subject'] = "Board Meeting"
            if clubDict[0]['board_confidence'] > 90:
                Story['Body'] = f"Hi {firstName},\nThings are going so well at the minute I could kiss you! I am such a picture of zen that I've even stopped getting on the wife's nerves. Keep it up buddy!\nLove you,\nGlenn"
            elif clubDict[0]['board_confidence'] > 70:
                Story['Body'] = f"Hi {firstName},\nJust a quick message to let you how the board meeting went today. We're happy with how things are going generally. Of course, there's always room for improvement so keep chipping away and let me know if I can help with anything. Keep up the hard work.\nWarm Regards,\nGlenn"
            elif clubDict[0]['board_confidence'] > 50:
                Story['Body'] = f"Hi {firstName},\nSome of the guys on the board have been raising their concerns about your leadership. I'll keep fighting your corner but we're going to have to string some wins together soon champ.\nBig Glenn's here if you need to chat.\nRegards,\nGlenn"
            else:
                Story['Sender'] = "Secretary to the Chairman"
                Story['Body'] = f"Hi {firstName},\nGlenn was sobbing into a pile of hobnobs after the board meeting today. I don't think that you'll be getting a message from him but I think you should know that it didn't go well. We need to win some matches {firstName}. Do you want me to take training this week? You look like you need a break & to be honest, I think I'd do a better job.n\Best,\nMorag"

        elif item == 15:
            Story['Sender'] = "Secretary to the Chairman"
            Story['Subject'] = "Computer systems"
            Story['Body'] = f"Hi {firstName},\nHeads up that I've got the new intranet up and running now so things should run much more smoothly around here. I can't believe that it took 25 years for Glenn to concede that computers aren't just 'a fad'. Me and Dave are smashing up the filing cabinets this afternoon and I'm putting on a bit of a buffet to celebrate - feel free to join.\nBest\nMorag"

        elif item == 16:
            Story['Sender'] = "The Chairman"
            Story['Subject'] = "Building Work"
            Story['Body'] = f"Hi {firstName},\nExcuse the noise today. We've got some guys in to extend the trophy cabinet. No pressure or anything (but it will need filling). Lol, only joking (but really, it will).\nWarm Regards\nGlenn"

        elif item == 17:
            Story['Sender'] = "Head Coach"
            Story['Subject'] = "Today"
            Story['Body'] = f"Hi {firstName},\nHeads up - I'm running a bit late for training today gaffer. I stopped off at Sports Direct to get some new training cones and the traffic was mental in the city centre. £3 for 20 cones though so swings and roundabouts. See you soon\nCheers\nDave"

        elif item == 18:
            club = getRandomClub(userId)[0]
            Story['Club_id'] = club['club_id']
            Story['Sender'] = f"Manager of {club['club_name']}"
            Story['Subject'] = "Catch Up"
            Story['Body'] = f"Hi {firstName},\nWe haven't been in touch much recently, just because we manage rival teams doesn't mean that we can't be friends. How about we go for a drink this weekend? I know a delightful wine bar where we won't be bothered by all the usual riff-raff. Say, 8pm? After Saturday's game. I promise not to get you too drunk and steal all of your secrets ; - )\nYours,\n{club['manager']}"

    return Story